### ISSUE TITLE
An unexpected error has occurred.

### ISSUE THREAD

**Issue by gc-o** [primecms/example-nextjs#1]
I'm quite interested in this project. I think Prime and Next.js has a lot of potential.

I tried to see the demo but when i click on a blog post it throws a bunch of errors on console and shows "An unexpected error has occurred."

It seems there is a CORS problem.

`Access to fetch at 'https://example-prime.herokuapp.com/graphql' from origin 'https://nextjs-example.primecms.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by birkir** [comment]
Damn. thanks for the heads up! I'm doing so many things at a time that this must have happened. Will check it out!

**Comment by birkir** [comment]
I accidentally remove the heroku app. Fixed!
